---
toc: false
---

### I've previously worked on a variety of projects from internships and classes! Here are some descriptions of my favorite ones:

#### **Use-and-Drop Members**, at Delta Dental Insurance
- Identified member behavior that abused Delta Dental’s individual insurance plans by using and dropping\
- Analyzed the costs associated with use-and-drop members using different metrics such as age and location\
- Presented our findings to actuarial managers and discussed a strategy to reduce overuse by 50%

#### [**Artist Diversity in US Museums**](https://museumdiversity.humspace.ucla.edu/), at UCLA
- Investigated factors causing disparity in representation using data from 16 prominent US museums\
- Cleaned through 10,000 entries of artist data to fix issues from the collection process using regex in R\
- Utilized Tableau to visualize relationships between artists and their defining characteristics

#### **Twitter Influence on Music**, at UCLA	
- Analyzed unstructured text while utilizing word frequency, dispersion, and KWIC methods\
- Transformed Twitter datasets using data wrangling techniques and tidyverse package in R (tidyr, dplyr)\
- Performed sentiment analysis to determine the overall mood of each tweet utilizing vader package in R\
